### ISSUE TITLE
CoreOS stable (1745.5.0)

### ISSUE THREAD

**Issue by jinxmcg** [Jacek-Kurasiewicz/coreos-essentials-installer#1]
Hi,

On Container Linux by CoreOS stable (1745.5.0)
I get this error:
```bash
docker run --rm  -v /etc:/mnt/etc  -v /root:/mnt/root  -v /home/core:/mnt/core  -v /opt/bin:/opt/bin  adelaar/coreos-essentials-installer install-mc.sh
```

```bash
mc has been succesfully installed ;)
am ~ # mc
/opt/bin/mc-bin/mc: error while loading shared libraries: __vdso_time: invalid mode for dlopen(): Invalid argument
am ~ #
```

Any clue?

Thanks

**Comment by k1n0b0n** [comment]
Yeah it seems like it does not work anymore with the same version.
I've been locked out of my CoreOS today after update !

Will reinstall it but is it possible to investigate on this issue because i really dig using this bag of tools ;)

**Comment by dadittoz** [comment]
To fix this error please change /opt/bin/mc contents to
```sh
#!/bin/sh
/opt/bin/mc-bin/libs/ld-linux-x86-64.so.2 --library-path /opt/bin/mc-bin/libs /opt/bin/mc-bin/mc "$@"
```
